### ISSUE TITLE
Actualizar Base de Datos

### ISSUE THREAD

**Issue by GutengMorgen** [AlumniONE/ecommerce-backend#20]
Durante la etapa actual del proyecto (Relaciones con Entidades), se han identificado algunos problemas en la base de datos:
- No existe la tabla order_cellphone para la relación ManyToMany order-cellphone.
- No existe la tabla cart_cellphone para la relación ManyToMany cart-cellphone.

Para avanzar a la siguiente etapa de desarrollo, es imperativo implementar las siguientes soluciones:
- Crear la tabla order_cellphone.
- Establecer la tabla cart_cellphone.

Esta es la actual EEM diagram de la base de datos:
![image](https://github.com/AlumniONE/ecommerce-backend/assets/73559673/0548976f-bc3c-4112-a8fe-eb29235260d0)

Además, se han detectado errores menores, tales como:
- Error en el tipo de dato: id_order emplea un tipo INT en lugar de BIGINT.
- Error tipográfico: la tabla cellphones utiliza id, mientras que otras tablas usan id_[nombre de la tabla].

El proposito de este issue crear un registro de opiniones sobre las modificaciones que se haran a la base de datos para que sea más óptima y tenga una mejor escalabilidad siguiendo buenas practicas.

**Comment by DataIndev** [comment]
Genial por el aporte, estás abierto a poder hacer un PR refactorizando el código así lo revisamos.?

**Comment by GutengMorgen** [comment]
por supuesto, lo hare lo antes posible, peeeero antes de hacer eso creo que seria mejor hacer una lista de cosas que se van a modificar en el db, hasta ahora tengo esto:

**blod** = contiene el foreign key, owner side

| Tables     | OneToOne     | OneToMany             | ManyToOne             |
|------------|--------------|-----------------------|-----------------------|
| carts      | users        |                       | cart_cell             |
| users      | **carts**    | orders                |                       |
| payments   |              | invoices              |                       |
| invoices   | orders       |                       | **payments**          |
| orders     | **invoices** |                       | **users**, order_cell |
| cellphones |              |                       | order_cell, cart_cell |
| cart_cell  |              | **cart, cellphones**  |                       |
| order_cell |              | **order, cellphones** |                       |

basandome en la descripcion de entidades y relaciones de entidades del trello


detalles menores:
- orders, users, invoice, payments, carts
	- cambiar id_[table_name] a id
- invoice
	- cambiar nombre de la tabla a invoices
- orders
	- cambiar data type id_order INT a BIGINT
	- cambiar dt product_id INT a BIGINT
	- cambiar nombre de product_id a cellphone_id
	- cambiar dt order_status JSON a VARCHAR(30)

preguntas:
porque invoice y product en la tabla orders tienen `default null`
