### ISSUE TITLE
Estandarizacion para los endpoint's de los controladores.

### ISSUE THREAD

**Issue by bonillasanchez98** [AlumniONE/ecommerce-backend#51]
Este nuevo Issue es creado con la finalidad de estandarizar una parte de la capa de los controladores del proyecto, con el objetivo de mantener e implementar buenas practicas, descoplamiento y que al momento de realizar alguna refactorizacion este pueda hacerse de forma optima.

Siguiendo las buenas practicas a los url de los endpoint's se adjuntan la siguiente imagen:
![url](https://github.com/AlumniONE/ecommerce-backend/assets/79986030/e95e9092-a843-48dd-afae-8de8dff62b31)

Donde:
- /V1: Indica la version del API
- /ecommerce: Es el contexto general del proyect
- /order: El recurso al cual se estara acceder, dependiendo del tipo de metodo. (GET, POST, PUT, DELETE, etc)

Para implementar esto en el proyecto lo que realice fue crear una clase que jugara el papel de "biblioteca", donde contara con atributos constantes y estaticos de tipo String, almancenando los diferentes tipos de path's o rutas de las cuales los endpoint's forman parte.

Como se muestra a continuación:
![image](https://github.com/AlumniONE/ecommerce-backend/assets/79986030/f8ff1c5f-9aec-45e6-af5e-cac7ba987f86)

La clase recibira el nombre del proyecto + el sufijo "Constant", en este caso "EcommerceConstant":
![image](https://github.com/AlumniONE/ecommerce-backend/assets/79986030/15923016-f5e1-42f4-b8eb-4bf95b290f32)

Como se pudo observar, cada parte del url del proyecto esta seccionada y almacenada en variables constantes de tipo String, segun sea la version, el contexto, los recusos (dentro de este los id's y los distintos objetos).

En la implementacion de esta clase en los diferentes controladores seria así:
![image](https://github.com/AlumniONE/ecommerce-backend/assets/79986030/7b89f2cf-0ee0-455f-b503-e180aba9ef63)
Siendo la parte seleccionada con el recuerdo azul la representacion a nivel de la url.

Y para finalizar, para ver el resultado de como se mostraria al equipo de frontend o cualquier otro cliente que quiera consumir el API, asi se le mostrara en la documentacion de Swagger:
![image](https://github.com/AlumniONE/ecommerce-backend/assets/79986030/cedccd81-b408-41fa-b280-a10b0305545c)
Siguiendo cada controlador un orden semantido claro y entendible.

Espero que esta pequeña explicacion sirva de ayuda y sea comprensible por el equipo de backend. Saludos.

**Comment by Tyrone073** [comment]
Sería genial agregar la estandarización de los endpoints, pero respecto al versionado no estoy tan seguro de si estaría bien. Mira esta página que habla sobre eso: [https://stackoverflow.com/questions/389169/best-practices-for-api-versioning](https://stackoverflow.com/questions/389169/best-practices-for-api-versioning).

[https://stackoverflow.com/questions/972226/how-to-version-rest-uris?noredirect=1&lq=1](https://stackoverflow.com/questions/972226/how-to-version-rest-uris?noredirect=1&lq=1).
